// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqbiP6qn332BzfGefCYsPwfxokHxU62k',
    appId: '1:721256453634:web:e0ad843fed3c08680cf91b',
    messagingSenderId: '721256453634',
    projectId: 'food-court-46778',
    authDomain: 'food-court-46778.firebaseapp.com',
    storageBucket: 'food-court-46778.firebasestorage.app',
    measurementId: 'G-LLQRFPZL0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75xrDMuPaTyF_3M-gr3Z1Ksm8HQOzlBk',
    appId: '1:721256453634:android:bcb63b3cb57dc9070cf91b',
    messagingSenderId: '721256453634',
    projectId: 'food-court-46778',
    storageBucket: 'food-court-46778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe29PCCdfnp61ZjgriUZy5X6ghglaEKr0',
    appId: '1:721256453634:ios:d4439d6aa4f575c00cf91b',
    messagingSenderId: '721256453634',
    projectId: 'food-court-46778',
    storageBucket: 'food-court-46778.firebasestorage.app',
    iosBundleId: 'com.example.foodCourt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe29PCCdfnp61ZjgriUZy5X6ghglaEKr0',
    appId: '1:721256453634:ios:d4439d6aa4f575c00cf91b',
    messagingSenderId: '721256453634',
    projectId: 'food-court-46778',
    storageBucket: 'food-court-46778.firebasestorage.app',
    iosBundleId: 'com.example.foodCourt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrqbiP6qn332BzfGefCYsPwfxokHxU62k',
    appId: '1:721256453634:web:5212502f28e8186e0cf91b',
    messagingSenderId: '721256453634',
    projectId: 'food-court-46778',
    authDomain: 'food-court-46778.firebaseapp.com',
    storageBucket: 'food-court-46778.firebasestorage.app',
    measurementId: 'G-8XZVFVM2HQ',
  );
}
